name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: sudo sh -e scripts/install_deps.sh

      - name: Build hyp and aboot firmware
        run: sudo sh -e scripts/build_hyp_aboot.sh

      - name: Extract MSM8916 firmware
        run: sudo sh -e scripts/extract_fw.sh

      - name: Create rootfs
        run: sudo sh -e scripts/debootstrap.sh

      - name: Build gadget-tool
        run: sudo sh -e scripts/build_gt.sh

      - name: Create images
        run: sudo sh -e scripts/build_images.sh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: files/*
          tag_name: ${{ github.run_number }}
          body: "Release based on commit ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}